# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 446d24937b04605ab0d07280c70fb9e57ea2fc868ced763715fe7e1203935119aa986911ae7cd29ae82d8e26394f3ba4fd1f7b2c14c4ed3a2d6d03693a0e65c1

test:
  secret_key_base: fb60b72d2d1df05b00f9b78ff74562f6a29b8974adfaaf83e0c86a3f8dfed53c84079795a81d01e45e6fadc3576dd171806949b1c0a7535ed492e35bfd780119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
